# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsmp.proto\x12\nsmartpower\" \n\rStatusRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x12TemperatureRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\'\n\x10TemperatureReply\x12\x13\n\x0btemperature\x18\x01 \x01(\t2T\n\rStatusChecker\x12\x43\n\x0b\x43heckStatus\x12\x19.smartpower.StatusRequest\x1a\x17.smartpower.StatusReply\"\x00\x32h\n\x12TemperatureChecker\x12R\n\x10\x43heckTemperature\x12\x1e.smartpower.TemperatureRequest\x1a\x1c.smartpower.TemperatureReply\"\x00\x32\xac\x01\n\x11SmartPowerService\x12\x43\n\x0b\x43heckStatus\x12\x19.smartpower.StatusRequest\x1a\x17.smartpower.StatusReply\"\x00\x12R\n\x10\x43heckTemperature\x12\x1e.smartpower.TemperatureRequest\x1a\x1c.smartpower.TemperatureReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSREQUEST']._serialized_start=25
  _globals['_STATUSREQUEST']._serialized_end=57
  _globals['_STATUSREPLY']._serialized_start=59
  _globals['_STATUSREPLY']._serialized_end=88
  _globals['_TEMPERATUREREQUEST']._serialized_start=90
  _globals['_TEMPERATUREREQUEST']._serialized_end=127
  _globals['_TEMPERATUREREPLY']._serialized_start=129
  _globals['_TEMPERATUREREPLY']._serialized_end=168
  _globals['_STATUSCHECKER']._serialized_start=170
  _globals['_STATUSCHECKER']._serialized_end=254
  _globals['_TEMPERATURECHECKER']._serialized_start=256
  _globals['_TEMPERATURECHECKER']._serialized_end=360
  _globals['_SMARTPOWERSERVICE']._serialized_start=363
  _globals['_SMARTPOWERSERVICE']._serialized_end=535
# @@protoc_insertion_point(module_scope)
